- name: Understanding Loops    
  hosts: rhel_group
  tasks:
     - name: Loop through a dictionary
       debug: var=item
       loop:
         - name: Jane
           country: US
         - name: JJ
           country: China

     - name: Print only selected
       debug: var=item.country
       loop:
         - name: "Jane"
           country: "US"
         - name: "JJ"
           country: "China"

     - name: Iterate a list 
       debug: var=item
       loop:
         - Jane
         - JJ
         - China

     # - name: Iterate a hash
     #   debug: var="{{ item.key }} -  {{ item.value }}"
     #   loop: "{{ names | dict2items }}" 
     #   vars:
     #      names:
     #           name1: "Jane"
     #           name2: "John"
  